### ISSUE TITLE
shutting down computer

### ISSUE THREAD

**Issue by ahmedo047** [pren/poltype#63]
Hi,

Poltype shuts down my computer when I run it for anthracene.  Please find the attached folder with all files.
Do you know that the problem is?
[anthracene.zip](https://github.com/pren/poltype/files/5589148/anthracene.zip)

**Comment by walkerbdev** [comment]
When I open the poltype.log, there is some sort of psi4 error in MP2
optimization of opt_2.log , I have run this molecule and pass this step
fine. Some suggestions, reduce number of processors, after a certain point
adding anymore does not give any additional benefit, and also try to
increase ram and disk memory. Then try again.

**Comment by ahmedo047** [comment]
Hi,

Can you please attach the `poltype.ini` file that you used for this molecule?

**Comment by walkerbdev** [comment]
Just 1) dont use all your CPU processors, I would say max 8, but even 8 may
not be any improvement over 6 for example. 2) Try to stick to rule of thumb
of no more than 80% process usage (maybe even less if on PC?, what other
programs are running and how much CPU resources are being taken up) , RAM
and disk. So those numbers will not be meaningful to give to you if you are
using your laptop and I am using a computing unit with a lot more
resources..

- Brandon

**Comment by ahmedo047** [comment]
Hi,

Just wanted to let you know that finally I got the anthracene parameters without having any errors by using the below parameters in the `poltype.ini`: 
```
structure=anthracene.sdf
numproc=8
maxmem=32GB
maxdisk=32GB
```

**Comment by walkerbdev** [comment]
Great! So you didnt change the maxmem and maxdisk, so Im guessing 16
numproc was too much.

**Comment by ahmedo047** [comment]
Hi,

I come across two problems because of the updated poltype:
**1)** Tinker gives the below error with the output file format of poltype:
```
INVERT  --  Cannot Invert a Singular Matrix
Tinker is Unable to Continue; Terminating the Current Calculation
```

**2)** The updated poltype gives an error while running it for anthracene molecule:
```
python3 /home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py poltype.ini
Poltype -- Polarizable atom typer of small molecules for the AMOEBA polarizable force field

Please cite:
Wu, J.C.; Chattree, G.; Ren, P.Y.; Automation of AMOEBA polarizable force field 
parameterization for small molecules. Theor Chem Acc. 

Version 2.3.0 February 2020

Copyright (c)  Johnny Wu, Gaurav Chattree, Brandon Walker, Matthew Harger and Pengyu Ren 2019

All Rights Reserved
##############################################################################################################

Calling: analyze /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.xyz -k /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.key e> version.out
Traceback (most recent call last):
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1336, in <module>
    poltype.main()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1005, in main
    params= self.GenerateParameters()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1224, in GenerateParameters
    mpole.rm_esp_terms_keyfile(self,self.key3fname)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/multipole.py", line 538, in rm_esp_terms_keyfile
    poltype.call_subsystem(cmdstr,True)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 935, in call_subsystem
    raise ValueError("ERROR: " + cmdstr+' '+'path'+' = '+os.getcwd())
ValueError: ERROR: sed -e '/\(.* none$\|^#\|^fix\|^potential-offset\)/d' anthracene.key_3 > anthracene.key_3_tmp path = /home/phy/Desktop/AMOEBA/test/poltype/anthracene_test
```

**Comment by walkerbdev** [comment]
Hello,

Please attach all input and output files into some downloadable link, then
I will take a look.

- Brandon

**Comment by ahmedo047** [comment]
Hi,

Please have a look at the attached files. 
As I said before **(1)** Tinker doesn't work properly with the output file format of poltype.
[ele1.0.zip](https://github.com/pren/poltype/files/5729699/ele1.0.zip)

(**2)** The updated poltype gives an error for anthracene molecule.
[anthracene_test.zip](https://github.com/pren/poltype/files/5728508/anthracene_test.zip)

**Comment by walkerbdev** [comment]
I have removed all *txt*, *key* and *xyz* files from your folder and
restarted, it seems to be working fine. If a prior key file had issues from
previous poltype version and that key file is still in directory, then
program will use that keyfile that had problems.

- Brandon

**Comment by ahmedo047** [comment]
Hi,

I just downloaded the updated poltype and deleted all files from the `anthracene_test` folder except `anthracene.sdf` and `poltype.ini`, then rerun the poltype. It still gives the error. Please have a look the attached `anthracene_test` folder.
```
python3 /home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py poltype.ini
Poltype -- Polarizable atom typer of small molecules for the AMOEBA polarizable force field

Please cite:
Wu, J.C.; Chattree, G.; Ren, P.Y.; Automation of AMOEBA polarizable force field 
parameterization for small molecules. Theor Chem Acc. 

Version 2.3.0 February 2020

Copyright (c)  Johnny Wu, Gaurav Chattree, Brandon Walker, Matthew Harger and Pengyu Ren 2019

All Rights Reserved
##############################################################################################################

Calling: analyze /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.xyz -k /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.key e> version.out
Traceback (most recent call last):
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1340, in <module>
    poltype.main()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1011, in main
    params= self.GenerateParameters()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1230, in GenerateParameters
    mpole.rm_esp_terms_keyfile(self,self.key3fname)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/multipole.py", line 538, in rm_esp_terms_keyfile
    poltype.call_subsystem(cmdstr,True)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 935, in call_subsystem
    raise ValueError("ERROR: " + cmdstr+' '+'path'+' = '+os.getcwd())
ValueError: ERROR: sed -e '/\(.* none$\|^#\|^fix\|^potential-offset\)/d' anthracene.key_3 > anthracene.key_3_tmp path = /home/phy/Desktop/AMOEBA/test/poltype/anthracene_test
```

[anthracene_test.zip](https://github.com/pren/poltype/files/5733872/anthracene_test.zip)

**Comment by walkerbdev** [comment]
Which OS and OS version are you using?
Thanks
- Brandon
________________________________

**Comment by ahmedo047** [comment]
I am using Ubuntu-20.04.1.

**Comment by walkerbdev** [comment]
Okay, if you take a look in your poltype.log, it mentions that there is no
key_3. Presumably something wrong with key_2 has occurred and so tinker
cannot perform electrostatic multipole fitting. I am not sure what you are
doing differently from me (not using latest version?), I have again removed
all keys, xyz files and txt files. The program finishes to completion, I
have attached the final parameters below.

https://utexas.box.com/s/d4ghm9hnnisf922fzl5k7gjcp6v2jl7n

**Comment by mquevill** [comment]
In #70, I had run into a similar issue, since the previous call to `potential` raised an error, which was an error associated with Tinker. Are you using the current `release` branch of Tinker? There was a bugfix to version 8.8.3 that addressed this issue in https://github.com/TinkerTools/tinker/commit/c4169e99fc06d14e767563be899e742b46ce6eba

**Comment by ahmedo047** [comment]
Hi @bdw2292 and @mquevill, 
I just reinstalled the current `release `branch of [Tinker](https://github.com/TinkerTools/tinker/) and downloaded the latest version of [poltype2](https://github.com/pren/poltype/tree/poltype2) but it didn't solve the problem. I still get the same error. @bdw2292 can you please attach the final parameters as zip file here?

**Comment by walkerbdev** [comment]
Hey,

Is this a similar problem for all molecules you try? Just pick a bunch of small ones.

Let me know if you can't access the zip file from this link below.

https://utexas.box.com/s/d4ghm9hnnisf922fzl5k7gjcp6v2jl7n
________________________________

**Comment by ahmedo047** [comment]
Hi,

I tested it on methanol and benzene as well. I get the same error for methanol:
`ValueError: ERROR: sed -e '/\(.* none$\|^#\|^fix\|^potential-offset\)/d' methanol.key_3 > methanol.key_3_tmp path = /home/phy/Desktop/AMOEBA/test/poltype/methanol_test`

But for benzene it gives a different error and hydrogen parameters are missing in `benzene.key_2 `and `benzene.key_3`:
`ValueError: /home/phy/Desktop/AMOEBA/test/poltype/benzene_test Warning: RMSPD of QM and MM optimized structures is high, RMSPD = 1.453`

I attached all the files of both molecules as zip files:
[methanol_test.zip](https://github.com/pren/poltype/files/5780293/methanol_test.zip)
[benzene_test.zip](https://github.com/pren/poltype/files/5780296/benzene_test.zip)

These errors are associated with `poltype2`?

**Comment by walkerbdev** [comment]
My guess is there is something messed up with the tinker installation you are using. Just yesterday, I was did a full fresh run of benzene and was adding extra features for poltype.

Could you put the tinker commit number you got the tinker version from?

-Brandon
________________________________

**Comment by ahmedo047** [comment]
Hi,
It seems that the problem was about `Tinker` installation. I don't get any errors for `benzene` and `anthracene `anymore after doing a fresh installation of `Tinker.` But `poltype` doesn't write out the f`inal.key` and `final.xyz` for `methanol` and gives the below error. Is it a bug? I attached the methanol files as zip file:
[methanol.zip](https://github.com/pren/poltype/files/5786099/methanol.zip)

```
Calling: analyze.x /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.xyz -k /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.key e> version.out
Traceback (most recent call last):
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1330, in <module>
    poltype.main()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 995, in main
    params= self.GenerateParameters()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1299, in GenerateParameters
    self.CheckTorsionParameters(self.key5fname,torsionsmissing)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 981, in CheckTorsionParameters
    raise ValueError("torsion parameters are all zero "+line+' path ='+os.getcwd())
ValueError: torsion parameters are all zero torsion 403 401 402 404 0.000 0 1 0 180.0 2 0 0.0 3
```

**Comment by walkerbdev** [comment]
Yes, there was a small bug. Please try redo git pull, then delete all files
and do fresh start.

Thanks,
Brandon

**Comment by ahmedo047** [comment]
Hi,

Unfortunately it still gives the same error. Please take a look at my input/output files: 
[methanol_test.zip](https://github.com/pren/poltype/files/5794504/methanol_test.zip)

Thanks.

**Comment by walkerbdev** [comment]
Can you try starting from the beginning, by deleting all files except
structure file input? Before I pushed update, I reproduced the error and
was able to complete full methanol parameterization.

Thanks
- Brandon

**Comment by walkerbdev** [comment]
actually, my bad, I had a keyword turned on that you did not in your file
(onlyrotbnd=), now it works with your input as well (new version).

**Comment by ahmedo047** [comment]
I think the bug is still there because it doesn't generate the methanol.key_5 and final.key.

**Comment by walkerbdev** [comment]
Yes, there was a missing line for reading in a dictionary in fragmenter.py
module. I have obtained final keys for this molecule. Please redownload,
then remove all xyz, key and txt files.

**Comment by ahmedo047** [comment]
It still doesn't write out the methanol.key_5 and final.key.

**Comment by walkerbdev** [comment]
Im not sure quite what to tell you. I have attached parameters below. Here
are some things that might help.

1) Maybe not latest poltype version?
2) Try removing *key*,*.txt and *xyz* files (including even in Fragment
folder just to be pedantic)
3) Restart poltype job

https://utexas.box.com/s/n5bvflxq4rbrng06807pgi1i5oy9wye8

- Brandon

**Comment by ahmedo047** [comment]
I use the latest poltype version. Well, I just checked the attached `1_2_Index_0-poltype.log` file in `/Fragments/1_2_Index_0` directory and noticed that it crashes (`forrtl: error (76): Abort trap signal`).
[1_2_Index_0-poltype.log](https://github.com/pren/poltype/files/5810786/1_2_Index_0-poltype.log)

**Comment by walkerbdev** [comment]
"Wed Jan 13 22:21:37 2021  Calling: cd
/home/phy/Desktop/projects/2021/amoeba/test/poltype/methanol_test/Fragments/1_2_Index_0/qm-torsion
&& psi4 1_2_Index_0-opt-1_1-4-331.psi4 1_2_Index_0-opt-1_1-4-331.log path =
/home/phy/Desktop/projects/2021/amoeba/test/poltype/methanol_test/Fragments/1_2_Index_0/qm-torsion
forrtl: error (76): Abort trap signal"
Seems like maybe your job was terminated externally with kill signal maybe?
What if you delete qm-torsion folder and restart.

**Comment by ahmedo047** [comment]
I just did it (deleted qm-torsion folder and restart) but it crashes with "`forrtl: error (76): Abort trap signal`" again. I tested it on different computers as well.

**Comment by leucinw** [comment]
It looks obvious to me that the error is related to intel Fortran, not
Python. So my suggestion is to install the latest Tinker using the GNU
Fortran compiler? After that, you can simply start with what Brandon
suggested.

**Comment by ahmedo047** [comment]
I installed the latest Tinker version with the GNU Fortran compiler but it didn't solve the problem. I attached all the files of methanol as zip file: 
[methanol_test.zip](https://github.com/pren/poltype/files/5811381/methanol_test.zip)

**Comment by walkerbdev** [comment]
Try using some of the binaries located here https://dasher.wustl.edu/tinker/

**Comment by leucinw** [comment]
I think I reproduced @ahmedo047 's issue. 
With a very fresh poltype (make a git pull now!), I am also able to get the final.key for methanol. See my files here 
https://biomol.bme.utexas.edu/~liuchw/methanol_test/
The only difference between my and his poltype.ini is that I am using maxdisk of 100GB. 
Hope this solves the problem.

**Comment by ahmedo047** [comment]
The error pops up in predicting the next geometric step. It is interesting that `polytpe` crashes with default `optbasisset` (`6-31G*`) but it works properly with a bigger `optbasisset `(e.g. `optbasisset=aug-cc-pvdz`) as suggested [here](https://github.com/psi4/psi4/issues/2084). Do you know that the problem is with default `optbasisset`?

P.S. using the binaries of Tinker, python-3.7 or increasing `maxmem`and/or `maxdisk` didn't help.

**Comment by walkerbdev** [comment]
Please attach the psi4 or gaussian input file and output file that the crash occured on.

Chengwen was able to reproduce error and determine QM crash because of memory reasons. I will see if I can reproduce the QM crash with your input settings and our QM software.
________________________________

**Comment by pren** [comment]
This sounds like Gaussian or pis4 issue on your computer. I suggest run the QM jobs standalone before poltype. Poltype folder has all the necessary input or you can generate yourself.


PENGYU REN, PhD

E.C.H Bantel Professor for Professional Practice

Biomedical Engr |  University of Texas at Austin

512-2321832  | https://biomol.bme.utexas.edu/
________________________________

**Comment by walkerbdev** [comment]
Please try with new poltype. I have reproduced the 4GB Psi4 crash and have
determined its an issue with Psi4s use of redundant internal coordinates.
Poltype will specify different coordinate system now.

**Comment by ahmedo047** [comment]
Please see attached zip file (Psi4's input/output files that the crash occurred on):
[met_files.zip](https://github.com/pren/poltype/files/5825180/met_files.zip)

**Comment by pren** [comment]
Try the latest poltype. PSI4 opt had issues with modredudant coordinates. We have adopted a better option. Our test with even 4GB mem works.


PENGYU REN, PhD

E.C.H Bantel Professor for Professional Practice

Biomedical Engr |  University of Texas at Austin

512-2321832  | https://biomol.bme.utexas.edu/
________________________________

**Comment by ahmedo047** [comment]
Finally problem was solved. The latest poltype finishes to completion. 
Thanks for your helps.
